package org.example;

import javax.swing.*;
import java.io.File;
import java.io.IOException;

public class JProgram extends javax.swing.JFrame {

    private DataManipulation dm = new DataManipulation();
    private FileCreator fc = new FileCreator();
    /**
     * Creates new form JProgram
     */
    public JProgram() throws IOException {
        initComponents();
        fc.createFiles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanelWindow = new javax.swing.JPanel();
        jButtonImport = new javax.swing.JButton();
        jButtonExport = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelImport = new javax.swing.JLabel();
        jLabelExport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonImport.setText("Импорт файла");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jButtonExport.setText("Экспорт файла");
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        jButtonExit.setText("Выход");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelImport.setText("Данные не загружены");

        jLabelExport.setText("Данные не выгружены");

        javax.swing.GroupLayout jPanelWindowLayout = new javax.swing.GroupLayout(jPanelWindow);
        jPanelWindow.setLayout(jPanelWindowLayout);
        jPanelWindowLayout.setHorizontalGroup(
                jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelWindowLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonExport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonImport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelImport)
                                        .addComponent(jLabelExport))
                                .addContainerGap(28, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWindowLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExit)
                                .addGap(52, 52, 52))
        );
        jPanelWindowLayout.setVerticalGroup(
                jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelWindowLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonImport)
                                        .addComponent(jLabelImport))
                                .addGap(52, 52, 52)
                                .addGroup(jPanelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonExport)
                                        .addComponent(jLabelExport))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(jButtonExit)
                                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {

        if (jLabelImport.getText().equals("Данные не загружены")) JOptionPane.showMessageDialog (null, "Данные еще не получены!", "Oшибка", JOptionPane.ERROR_MESSAGE);
        else if (jLabelExport.getText().equals("Данные выгружены")) JOptionPane.showMessageDialog (null, "Данные уже выгружены!", "Oшибка", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                dm.writeResultsToExcel("./Result.xlsx");
                jLabelExport.setText("Данные выгружены");
            } catch (IOException e) {
                JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        String currentDir = System.getProperty("user.dir");
        chooser.setCurrentDirectory(new File(currentDir));
        chooser.setDialogTitle("Выберите файл");

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File file = chooser.getSelectedFile();
                dm.setData(String.valueOf(file));
                jLabelImport.setText("Данные загружены");
                jLabelExport.setText("Данные не выгружены");
            }catch (Exception r){
                JOptionPane.showMessageDialog (null, "Ошибка чтения файла", "Oшибка", JOptionPane.ERROR_MESSAGE);
                jLabelImport.setText("Данные не загружены");
                jLabelExport.setText("Данные не выгружены");
            }
        }

    }

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JLabel jLabelExport;
    private javax.swing.JLabel jLabelImport;
    private javax.swing.JPanel jPanelWindow;
    // End of variables declaration
}
